Repository telepresenceio/telepresence, pull requests merged in 2021-07, with the labels that each got.

#1831 Make intercept recover from deletion of intercepted pod.
  .circleci/config.yml
  CHANGELOG.md
  cmd/traffic/cmd/agent/client.go
  cmd/traffic/cmd/agent/state.go
  cmd/traffic/cmd/manager/internal/state/state.go
  go.mod
  go.sum
  pkg/client/actions/manager_client.go
  pkg/client/cli/cliutil/daemon.go
  pkg/client/cli/telepresence_test.go
  pkg/client/connector/intercept.go
  pkg/client/connector/traffic_manager.go
  pkg/dpipe/dpipe.go
  pkg/forwarder/forwarder.go
  pkg/tun/device_darwin.go
Labels: w:1

#1884 Ensure that the manager's RoleBinding appoints the correct Role.
  CHANGELOG.md
  charts/telepresence/templates/trafficManagerRbac/namespace-scope.yaml
  pkg/install/resource/tm_role.go
  pkg/install/resource/tm_role_binding.go
Labels: t:bug, w:4

#1886 Avoid adding all subcommands except "daemon-foreground" for root daemon.
  CHANGELOG.md
  cmd/telepresence/main.go
  pkg/client/cli/cmd.go
  pkg/client/daemon/service.go
Labels: t:bug, w:4

#1909 Improve systemd-resolved based DNS resolver stability and handover to the overriding one
  CHANGELOG.md
  pkg/client/daemon/dbus/resolved.go
  pkg/client/daemon/outbound.go
  pkg/client/daemon/outbound_darwin.go
  pkg/client/daemon/outbound_linux.go
  pkg/client/daemon/resolved_linux.go
  pkg/client/daemon/tunrouter.go
Labels: t:bug

#1913 Fix nil pointer crash when doing telepresence current-cluster-id
  CHANGELOG.md
  pkg/client/cli/cmd.go
Labels: t:bug

#1920 Fixed systemd-resolved sanity check failure if the default iface has ~. domain
  CHANGELOG.md
  pkg/client/daemon/resolved_linux.go
Labels: t:bug

#1922 Make references in agent's environment work
  CHANGELOG.md
  cmd/traffic/cmd/agent/agent.go
  cmd/traffic/cmd/manager/internal/mutator/agent_injector_test.go
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-mp-tc-0.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-mp-tc-1.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-mp-tc-2.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-mp-tc-3.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-0.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-1.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-10.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-11.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-2.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-3.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-4.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-5.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-6.input.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-6.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-7.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-8.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/deployment-tc-9.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/replicaset-mp-tc-0.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/replicaset-tc-0.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/statefulset-mp-tc-0.output.yaml
  pkg/client/connector/userd_trafficmgr/testdata/addAgentToWorkload/cur/statefulset-tc-0.output.yaml
  pkg/install/container.go
Labels: t:bug

#1911 Fix panic when passing incorrect argument to the `--http-match` option
  CHANGELOG.md
  pkg/client/cli/cmds_intercept.go
Labels: t:bug
