Repository telepresenceio/telepresence, pull requests merged in 2021-09, with the labels that each got.

#2031 Bump vm-linux to ubuntu-2004:202010-01
  .circleci/config.yml
Labels: w:2

#2030 Traffic-manager needs permissions to get namespaces
  .circleci/config.yml
  CHANGELOG.md
  build-aux/main.mk
  charts/telepresence/templates/trafficManagerRbac/cluster-scope.yaml
Labels: t:bug, p:high, w:2

#2042 Let daemons open their socket listeners prior to performing other tasks.
  CHANGELOG.md
  pkg/client/cli/cliutil/connector.go
  pkg/client/cli/cliutil/daemon.go
  pkg/client/connector/command.go
  pkg/client/daemon/service.go
  pkg/client/sockets.go
  pkg/client/sockets_unix.go
  pkg/client/sockets_windows.go
Labels: t:bug

#2065 Don't block all outbound traffic while handling a control message.
  CHANGELOG.md
  pkg/connpool/dialer.go
  pkg/tun/tcp/handler.go
  pkg/tun/tcp/tmgr.go
Labels: w:4

#2064 Provide environment variable TELEPRESENCE_INTERCEPT_ID during intercept.
  CHANGELOG.md
  pkg/client/cli/cmds_intercept.go
  pkg/client/cli/telepresence_test.go
  pkg/client/cli/testdata/hello/server.py
Labels: w:4

#2066 Let the telepresence status command report correct DNS IP
  CHANGELOG.md
  pkg/client/cli/cmd.go
  pkg/client/cli/cmd_status.go
  pkg/client/daemon/outbound.go
  pkg/client/daemon/service.go
Labels: w:4

#2093 Improve traffic-managers podCIDR discovery
  CHANGELOG.md
  build-aux/main.mk
  charts/telepresence/README.md
  charts/telepresence/templates/deployment.yaml
  charts/telepresence/values.yaml
  cmd/traffic/cmd/manager/internal/cluster/info.go
  cmd/traffic/cmd/manager/internal/cluster/nodewatcher.go
  cmd/traffic/cmd/manager/internal/cluster/nodewatcher_test.go
  cmd/traffic/cmd/manager/internal/cluster/podwatcher.go
  cmd/traffic/cmd/manager/internal/cluster/podwatcher_test.go
  cmd/traffic/cmd/manager/internal/mutator/agent_injector.go
  cmd/traffic/cmd/manager/manager.go
  cmd/traffic/cmd/manager/managerutil/ctx.go
  cmd/traffic/cmd/manager/managerutil/envconfig.go
  cmd/traffic/cmd/manager/managerutil/envconfig_test.go
  cmd/traffic/cmd/manager/service_test.go
  pkg/client/cli/telepresence_test.go
  pkg/client/daemon/tunrouter.go
  pkg/subnet/set.go
  pkg/subnet/set_test.go
Labels: t:bug, t:feature

#2094 context in intercept questions, default port 80
  CHANGELOG.md
  cmd/traffic/cmd/manager/internal/state/state.go
  cmd/traffic/cmd/manager/service.go
  cmd/traffic/cmd/manager/systema.go
  pkg/client/cli/cmd_preview.go
  pkg/client/cli/cmds_intercept.go
  pkg/client/connector/userd_grpc/service_proxy.go
  rpc/manager/manager.pb.go
  rpc/manager/manager.proto
  rpc/manager/manager_grpc.pb.go
Labels: t:bug, t:feature
