Repository telepresenceio/telepresence, pull requests merged in 2021-05, with the labels that each got.

#1576 Updated the brew installation instructions
  docs/macros.html
Labels: stale

#1529 Update environment-setup script
  ci/setup-gcloud.sh
  environment-setup.sh
Labels: v1

#1702 Improve smoke tests
  smoke-tests/run_smoke_test.sh
Labels: v2

#1706 website: "Datawire" → "Ambassador Labs"
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/USERS.md
  docs/_layouts/website/page.html
  docs/about.html
  docs/announcing-telepresence-2.html
  docs/case-studies/bitnami.html
  docs/case-studies/engel-volkers.html
  docs/case-studies/index.html
  docs/case-studies/iris-tv.html
  docs/case-studies/sight-machine.html
  docs/case-studies/verloop.html
  docs/community.html
  docs/discussion/how-it-works.md
  docs/discussion/why-telepresence.md
  docs/index.html
  docs/js/datawire-breadcrumb.js
  docs/macros.html
  docs/package.json
  docs/reference/changelog.md
  docs/reference/community.md
  docs/reference/developing.md
  docs/reference/limitations.md
  docs/reference/methods.md
  docs/reference/proxying.md
  docs/reference/related-projects.md
  docs/reference/upgrade.md
  docs/reference/usage_reporting.md
  docs/reference/windows.md
  docs/styles/website.css
  telepresence/cli.py
Labels: a:docs

#1707 website: Add <link rel="canonical"> tags
  docs/_layouts/website/page.html
  docs/about.html
  docs/announcing-telepresence-2.html
  docs/case-studies/bitnami.html
  docs/case-studies/engel-volkers.html
  docs/case-studies/index.html
  docs/case-studies/iris-tv.html
  docs/case-studies/sight-machine.html
  docs/case-studies/verloop.html
  docs/community.html
  docs/index.html
Labels: a:docs

#1690 Improve license support
  cmd/traffic/cmd/agent/client.go
  cmd/traffic/cmd/manager/envconfig.go
  cmd/traffic/cmd/manager/internal/state/state.go
  cmd/traffic/cmd/manager/service.go
  pkg/client/cli/license_test.go
  pkg/client/cli/testdata/license
  pkg/client/connector/install.go
  pkg/client/connector/intercept.go
  pkg/client/connector/service_proxy.go
  rpc/manager/manager.pb.go
  rpc/manager/manager.proto
  rpc/manager/manager_grpc.pb.go
Labels: v2

#1685 Get rid of sshd in traffic-manager
  CHANGELOG.md
  cmd/traffic/cmd/agent/forwarder.go
  cmd/traffic/cmd/manager/internal/conntunnel/handler.go
  cmd/traffic/cmd/manager/internal/state/state.go
  cmd/traffic/cmd/manager/manager.go
  cmd/traffic/cmd/manager/service.go
  pkg/client/connector/intercept.go
  pkg/client/connector/traffic_manager.go
  pkg/client/daemon/outbound.go
  pkg/client/daemon/tunrouter.go
  pkg/connpool/connid.go
  pkg/connpool/context.go
  pkg/connpool/control.go
  pkg/connpool/dialer.go
  pkg/connpool/listener.go
  pkg/connpool/message.go
  pkg/connpool/pool.go
  pkg/connpool/stream.go
  pkg/iputil/parse.go
  pkg/tun/route_darwin.go
  pkg/tun/tcp/handler.go
  pkg/tun/tcp/tmgr.go
  pkg/tun/udp/dnsinterceptor.go
  pkg/tun/udp/handler.go
  rpc/daemon/daemon.pb.go
  rpc/daemon/daemon.proto
Labels: v2, w:4

#1686 Get rid of sshd in the traffic-agent
  CHANGELOG.md
  base-image/Dockerfile
  cmd/traffic/cmd/agent/agent.go
  cmd/traffic/cmd/agent/state.go
  cmd/traffic/cmd/manager/data.go
  cmd/traffic/cmd/manager/service.go
  k8s/manager.yaml
  pkg/client/cli/intercept_state.go
  pkg/client/connector/install.go
  pkg/client/connector/install_actions.go
  pkg/client/connector/intercept.go
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-initializer.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-mp-tc-0.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-mp-tc-1.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-mp-tc-2.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-mp-tc-3.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-0.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-1.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-10.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-11.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-2.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-3.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-4.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-5.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-6.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-7.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-8.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/deployment-tc-9.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/replicaset-mp-tc-0.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/replicaset-tc-0.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/statefulset-mp-tc-0.output.yaml
  pkg/client/connector/testdata/addAgentToWorkload/cur/statefulset-tc-0.output.yaml
  pkg/dpipe/dpipe.go
  rpc/manager/manager.pb.go
  rpc/manager/manager.proto
Labels: v2, w:4

#1687 Move all DNS resolution to the cluster.
  CHANGELOG.md
  cmd/traffic/cmd/agent/client.go
  cmd/traffic/cmd/manager/internal/state/state.go
  cmd/traffic/cmd/manager/internal/state/state_test.go
  cmd/traffic/cmd/manager/service.go
  k8s/client_rbac.yaml
  pkg/client/cli/telepresence_test.go
  pkg/client/connector/detect_ingress.go
  pkg/client/connector/install.go
  pkg/client/connector/k8s_cluster.go
  pkg/client/connector/outbound.go
  pkg/client/connector/service.go
  pkg/client/connector/service_proxy.go
  pkg/client/connector/traffic_manager.go
  pkg/client/daemon/dns/dns.go
  pkg/client/daemon/outbound.go
  pkg/client/daemon/outbound_darwin.go
  pkg/client/daemon/outbound_linux.go
  pkg/client/daemon/resolved_linux.go
  pkg/client/daemon/service.go
  pkg/client/daemon/tunrouter.go
  pkg/client/scout.go
  pkg/connpool/dialer.go
  pkg/iputil/ipkey.go
  pkg/iputil/ipnet.go
  pkg/iputil/ips.go
  pkg/subnet/byte_set.go
  pkg/subnet/byte_set_test.go
  pkg/subnet/subnet.go
  pkg/subnet/subnet_test.go
  pkg/subnet/testdata/ips.txt
  pkg/tun/tcp/tmgr.go
  rpc/daemon/daemon.pb.go
  rpc/daemon/daemon.proto
  rpc/daemon/daemon_grpc.pb.go
  rpc/daemon/iptables.pb.go
  rpc/daemon/iptables.proto
  rpc/manager/manager.pb.go
  rpc/manager/manager.proto
  rpc/manager/manager_grpc.pb.go
Labels: v2, w:4

#1744 Let sshfs allow root on volume mounts
  CHANGELOG.md
  pkg/client/connector/intercept.go
Labels: t:bug, v2, w:4
